### ISSUE TITLE
Being called "untrustworthy" on a public slideshow, and subsequently blocked from commenting

### ISSUE THREAD

**Issue by christopherreay** [solid/community#59] opened 2019-02-25 08:44 UTC
[image of comment stream on google slides](https://christopherreay.com/fileStorage/wat.png)

Yesterday (24 Februrary, 2019) I was invited by Timothy Holborn from a private facebook group to the Solid gitter channel. I spent a good couple of hours reading and responding with various people, and had some valuable interactions.

as you can see from the image, this morning at 7:30, I clarified my meaning regarding my opinion about some content regarding blockchain, which is a field I have worked in.

I feel no animosity to @mediaprophet, but experience has taught me to nip these kinds of issues in the bud as quickly as possible.

Specifically to make a suggestion, I would like:
* @mediaprophet to consider that their emotional response is unwarranted, and therefore feel more supported in the World
* the comment they made to be deleted from the slides

secondary
* Id like to actually engage in the conversation I suggested about blockchain, since it is positive to the Solid community

**Comment by christopherreay** [comment] 2019-02-25 08:46
Further comments on this topic in the gitter:

Mitzi László @Mitzi-Laszlo 08:34
@christopherreay you can submit an issue to the community repo describing what happened and how it relates to the code of conduct https://github.com/solid/community/blob/master/code-of-conduct.md
You can read how this will get processed on https://github.com/solid/community

mediaprophet @mediaprophet 08:36
@Mitzi-Laszlo - might be better if there was a private address.
if you’d like me to publish the basis to why it was i stated he was untrustworthy - cool
but in my opinion - should i be found to have acted in good judgement, you’ll be obligated to throw me a party ;)
so, i don’t mind.

jayDayZee @christopherreay 08:37
Absolutely I would like to see that published. Either here, or probably better, in the github?
Ill create an issue and post the link here

mediaprophet @mediaprophet 08:38
https://www.youtube.com/watch?v=pRGhrYmUjU4

End of the day - even relates to convicts, which is what will protect him.

So - @Mitzi-Laszlo - let me know how getting targeted, ends-up with a good outcome for the innocent.


jayDayZee @christopherreay 08:45
Hi, Tim, here you go: solid/community#59

**Comment by christopherreay** [comment] 2019-02-25 09:00
> mediaprophet @mediaprophet 08:38
https://www.youtube.com/watch?v=pRGhrYmUjU4

nb: this is a video about "Human Rights"
> End of the day - even relates to convicts, which is what will protect him.
> So - @Mitzi-Laszlo - let me know how getting targeted, ends-up with a good outcome for the innocent.

I object also to being called a "convict" in the gitter channel.

**Comment by christopherreay** [comment] 2019-02-25 09:16
> mediaprophet @mediaprophet 09:13
> @Mitzi-Laszlo re: dignity / privacy works - it's impossible to respond to these attacks in a manner that does not breach trust - for a circumstance where i elected not to engage further with someone due to behaviours i considered to be un-trustworthy.
> As noted - when the assessment is made, it may be the case that i'm owed a party ;)

Looks to me like someone who emotionally reacted to a situation, and is now looking for ways to hide that.

**Comment by mediaprophet** [comment] 2019-02-25 09:34
The claims contain an array of false and misleading statements which for reasons relating to the UDHR cannot be aired publicly as to resolve this undesirable circumstance, as does in-turn illustrate further breaches to the principles outlined in the UDHR consequentially.
https://www.un.org/en/universal-declaration-human-rights/

**Comment by Mitzi-Laszlo** [comment] 2019-02-25 21:06
@mediaprophet @christopherreay who was the owner of the google account that the slides were being shared with?

**Comment by Mitzi-Laszlo** [comment] 2019-02-25 21:33
@mediaprophet @christopherreay Where can I find a coherent overview of both of your perspectives on the topic of Solid and Blockchain?

**Comment by MattDorrian** [comment] 2019-02-26 00:00
Opinions covered by 'Freedom of expression' often result in clashes guys its not personal.  Dust yourselves off.  Solid on Blockchain is this something that is happening as we speak?

**Comment by mediaprophet** [comment] 2019-02-26 02:41
The context of this entire thing is made intentionally misleading and has
been executed in a format that is intentially seeking to do damage.

'blocked from commenting' refers to a draft documents i was producing
myself, had only spend a few hours doing so, which now is dragging me into
a drama that must be held in a public frame - like a kid picking a fight in
a school-yard seeking to have the school cheering them on - fairly
disgusted.

so - to feed this reprehensible ethical design - here's my public documents
in question - note the date-stamps, as if the events were put into
chronological order it would help intepret what was going on,

-
https://docs.google.com/document/d/1pJT2Bz1mNbwAFFL44kbh9_LZPqr_CMRVly38l69JEEQ/edit?usp=sharing
-
https://docs.google.com/presentation/d/1TaWE3d78rsmg2zflL1yqjPv-Pnu0YMDy-FVpvxYG1XM/edit?usp=sharing


Now, the problem is of course - that whilst i made the documents i was
working on with community (although non-had time to contribute as yet -
other than these comments in question) i had to make the document private
as i couldn't delete them, as is the functionality provided in google docs.

furthermore - there are group chats held in private  (not withstanding some
other, worrying problems) which i'm not sharing - whilst noting, those
involved with it will be sent the link to this public bullying session;
and,

Well - consequentially i might note, that if someone wants to speak with
noam chomsky or TimBL (particularly if it is the case they understand RDF)
- they needed 'take a person out', rather - just use google, or in some
cases - foaf - and do it themselves.

FWIW - in the investment market (also enterprise sales related business
systems) it is commonplace that 'investors' may try to ensure the amount
they need to invest to get the product - an example is like
https://www.youtube.com/watch?v=JlwwVuSUUfc

I suggest solid or inrupt moreover - does not build business systems that
inadvertently lend support for this type of commercially motivated
behaviour. as illustrated in MY diagram
https://www.webizen.net.au/wp-content/uploads/2018/10/infosphere_actor_objects.svg
the moral responsibility is held with the individual, whereas the ethical
responsibility is held with the group.

this is, in my opinion, the wrong way of dealing with an issue such as is
the case in this circumstance where much of the pertinent information is
held permissively in confidence.

I also noted - perhaps if this is resolved in a manner that exonerates me,
that perhaps i deserve a party - i don't think that'll happen.  that's not
how this community works.  I suggest that problem is fixed.

**Comment by Mitzi-Laszlo** [comment] 2019-02-26 08:58
Can we focus on the content and deescalate the tone here please, this conversation is not productive.  I'm afraid you both are interested in similar content so will have to reconcile working together. I'd like to invite you both to taking a less personal more focused approach. Perhaps you could both apologise to each other and accept each others apology?

**Comment by mediaprophet** [comment] 2019-02-26 09:36
I didn't start it.  I started a document, and now have a public complaint
made.  If you believe the complaint is without merit, i suggest you resolve
it in consideration of your findings no-matter who finds the outcome
inconvenient.

**Comment by mediaprophet** [comment] 2019-02-26 09:39
also - please point me to the policies about how people are entitled to
produce and share documents they author about solid, in their own accounts,
as actions undertaken independently by them, etc.

If possible also - please point me to how such actions reasonably provide
means to bring about this series of policies, and how it is that if the
process is found to be punitive - that the implications of this are also
considered in relation to any form of equitable remedy - community
standards framework.

This is not in any way due to the manner in which i wanted to spend my
time.  but since it's been forced upon me, lets process it.

**Comment by Mitzi-Laszlo** [comment] 2019-02-26 09:48
This is not so much an exercise of finding a guilty party and punishing rather an exercise of building bridges.

**Comment by mediaprophet** [comment] 2019-02-26 10:39
Really?
So, why did the ticket get made...
https://gitter.im/solid/chat?at=5c73a880c82c68509e316315
https://gitter.im/solid/chat?at=5c73a86ac82c68509e316204

For the purpose of Asymmetrical responsibility?

My view is that this is Ridiculous.; That someone writes negative (and
moreover unproductive) comments on work I am doing  (whilst other
behaviours occur privately that all together cause a level of discomfort)
then goes about causing as much damage as possible AFTER i've already said
he should go his own direction and that this is part of how solid is
defined - that it is open-source and open-standards - yet he THEN decides
to write such comments and proceed in this manner - and as the facts
fall.out, after it's all laundered, the resolution is - go befriend the man.

I do not believe such statements would be made if the finding a of the
investigation were entirely different, yet as has been taken without
consent - hours of my time - i choose to bow out without putting any
further expectations upon anyone - whereby ethical illustrations of
judgement methodologies are now available clear-as-day.

I hope you employ him as your lead developer, obviously this thread
provides merit for his trust-worthiness and how it is that my independent
and personal considerations as is now laundered - were entirely baseless. I
hope that overtime - the merit of this approach and the relative behaviours
are found to be 'meritorious' and with good ethical foundations - as they
overtime defining how wrong i am, and that this is all well set-out as to
ensure those most important are 'on the right side of history', if indeed
the project solid is working towards ensuring any such form of
consideration is indeed important.

I'm going to set-out somewhere else to pursue the works, lending upon the
same stature i stated to the man prior to his continued attacks - in that -
perhaps it'll be better for solid that there are different ethically
embodied structures of how it is solid is defined and developed.   Therein,
i've already started working on a different structure for handling
complaints and am considering how a bond or fee may be paid up-front as to
ensure there is indeed a penalty for wrong-doings upon others, which may
in-turn be addressed in a manner that ensures a qualitative review in a
manner that preserves the confidences of others.

finally - it's media prophet - not media profit
https://gitter.im/solid/chat?at=5c73a27200aa630d9a0a5bbe - reason being,
that as i did the work from finding the TV-Anytime CRID value stuff, to
helping form work that resulted in project kangaroo and HbbTV (back in
2007) - as i got sick of people taking my work for nothing, then not
knowing how to implement it - then coming back and asking for help, once
they'd burn a bunch of cash via some ego-trip, that in some cases, included
injury caused along their journeys.

so - media prophet - meaning plural form of medium
https://www.google.com/search?q=define+media and prophet - as in, i don't
want to tell someone later - i told you so.  it's in the brand, and is
straight forward.

noting also - given the incredible international contributors involved in
this project - the terms have much lesser purpose in said circles than it
would otherwise have with regional projects, particularly thee small ones.

anyhow.  until otherwise notified, i'll work elsewhere and post to the
lists as required for interop related matters.  I'll also be ensuring the
basic stuff is available permissively, as has been the reason for investing
so many years in the w3c works as to bring about - well..

i guess we all stand for values by out actions (and at times also, lack
thereof).   I'm not going to publish a bunch of private materials to defend
myself in this manner by a person who harbours no responsibility for the
damage caused - indeed moreover - seeks to benefit from such choices - i
guess, it's about cultural development, to which I accept the decisions
made by management..

cya.

**Comment by HCKgit** [comment] 2019-02-26 13:39
Please Close this spat.   Is is so so unnecessary.  These things are personal and the net is a big place.

**Comment by mediaprophet** [comment] 2019-02-26 13:56
apparently the policy is to leave it up for another 10+ days...

nb: https://gitter.im/solid/chat?at=5c752a288a7def0752dc885c

anyhow.  I'm going to go work on forming a safe-zone elsewhere...

https://www.youtube.com/watch?v=dRFrXGkYjhM
https://www.youtube.com/watch?v=rCplocVemjo

rule of law means that if a dispute is raised, then the issues are
addressed no-matter who is at fault - rule of law is not about facilitating
a public witch-hunt.

the answer cannot be that i am either censured, or no action is done, the
thread is left, and it's suggested i befriend the man - when the
repercussive framework makes the considerations i made about my personal
choices of who i personally want to work with (or who i do not, and for
what reason) are both illustrated out of context, in a damaging form,
without repercussive effects - as though these are the sorts of qualities i
should look for in people i want to consider trust-worthy...

meh.

solid community structures needs diversification anyhow.  the tech is
designed to be all about decentralisation.  not as though there's only one
flavour of linux, and i'm sure there's all sorts of ethical, community
related differences of cultural attitudes, etc..

**Comment by mikeadams1** [comment] 2019-02-26 14:36
@christopherreay Are you a convict, or have you been previously convicted of a crime? If not, I believe it's ok to pull @mediaprophet card on that. @mediaprophet If @christopherreay is not a convict, you should apologize without delay.

**Comment by mediaprophet** [comment] 2019-02-26 14:40
Watch the video in question. it states clearly that human rights are for
all people, including convicts.  the statement was about human rights.

I suggest given the contextualisation was out - mike gets it right back at
him.  but then again - this is all about a school yard fight styled
community environment, so, it's free hits all round.

therein - i'm out.

but please - make a list - i mean, without the private information - its
all out of context - so this is about the people who leverage off
hearsay...  would be good to know who those people are...

**Comment by Mitzi-Laszlo** [comment] 2019-02-26 16:44
What are you hoping to achieve from this conversation? Thank you for keeping it confined to this pull request rather than other channels that include more people and may want to focus on other things. Just to be clear I will not deliver a judgement or outcome after 14 days, I will simply close the pull request. If someone choses to block people from a privately controlled google slides, I'm afraid it's out of my remit to comment on that. All I can do is to advise you both to keep to the content and keep the conversation civil.

**Comment by christopherreay** [comment] 2019-02-26 17:29
What I have been pointing out is that in the claims I have seen regarding "solid vs blockchain" - specifically "why solid is better", I have seen both inaccurate claims about blockchain, and... unsubstantiated claims about solid. Im sure this will feed out into more detail later, and that solid will stand up to the letter of its convictions

**Comment by mediaprophet** [comment] 2019-02-26 18:09
TimBL has a WebID.

Spec is https://dvcs.w3.org/hg/WebID/raw-file/tip/spec/tls-respec.html

The decisions made prior to this thread or the comments on my documents -
led me to have a particular consideration, and whilst i share information
shared with me that is consistent with prior examples.

i don't believe i should be required to have anything to do with him.  he
behaves in a manner that lacks consideration of consent and/or human agency.

Anyhow.

Have a party between yourselves.  perhaps it's something worth
celebrating...


[image: 0.png]
[image: 1.jpg]
[image: 1.png]
[image: 2.jpg]
[image: 3.jpg]
[image: 4.jpg]
[image: 5.jpg]

**Comment by christopherreay** [comment] 2019-02-26 20:02
all I can say is that I'm sorry you are interpreting what you are reading in such a way..all lve done is try to have constructive and friendly conversation with you.

I wish you all the best of luck with your journey

**Comment by mediaprophet** [comment] 2019-02-26 20:42
Christopher -  i am not able to afford you any luck, given the choices you
have made.  It's more than 10k of my time so far, and the clock keeps
ticking; and that's without even having done a damage assessment...

see the top part of the info -
https://www.webizen.net.au/wp-content/uploads/2018/09/Credential-enabled-Identity-5.svg

note:
https://www.w3.org/community/credentials/2014/08/06/call-for-participation-in-credentials-community-group/

so, you get in touch with me, and in the period of about a week - go about
making an attempt to cause severe injury to my life, having been provided
enough information to ensure, beyond doubt, you know exactly what you were
doing...  and you then label me with mental health issues, which is
irrelevant - unless you want to publish your psychiatric report exonerating
you from all responsibility for your actions.

i'll keep going - and seek to resolve this matter externally, as frankly -
i don't see where any solid community whoever has any jurisdiction at all
over any of this - indeed, for them, i'd consider it a liability.

as was the case earlier.  pity things have to be made clear as mud. ;(

**Comment by christopherreay** [comment] 2019-02-26 21:46
I haven't accused you of anything

we met on a group brought together through a mutual friend.

every single conversation we have ever had has been in front of other people. you are the only one raising the idea that I am attacking you. I have nothing to gain from attacking you..all I have done is engage in friendly, constructive communication.

**Comment by melvincarvalho** [comment] 2019-02-27 05:15
Well that escalated quickly!  @Mitzi-Laszlo thanks for looking at this.  I'd like to suggest a slightly different, or other, approach.

@mediaprophet is a venerable member of our community that I have known for many years.  I know he takes great pride in helping newer members and has a great facility with the English language.  The word mentioned in quotes in the title of this issue, I am sure was used inadvertently, *as pertains to a member of our own community*.  A better way to phrase it may have been "I dont trust technical X about" with regards to a block chain in or *a specific argument*.  It is only right and proper that we allow a chance to change the wording or withdraw that particular term, if it is part of a public record.  I am sure that this opportunity will be taken, and I think already the work is no longer public.

In a general sense I find the following paragraphs from the NextCloud community helpful in cases like these : 

> Support others in the community

> Our community is made strong by mutual respect, collaboration and pragmatic, responsible behavior. Sometimes there are situations where this has to be defended and other community members need help.

> If you witness others being attacked, think first about how you can offer them personal support. If you feel that the situation is beyond your ability to help individually, go privately to the victim and ask if some form of official intervention is needed. Similarly you should support anyone who appears to be in danger of burning out, either through work-related stress or personal problems.

> When problems do arise, consider respectfully reminding those involved of our shared Code of Conduct as a first action. Leaders are defined by their actions, and can help set a good example by working to resolve issues in the spirit of this Code of Conduct before they escalate.

> Get support from others in the community

> Disagreements, both political and technical, happen all the time. Our community is no exception to the rule. The goal is not to avoid disagreements or differing views but to resolve them constructively. You should turn to the community to seek advice and to resolve disagreements and where possible consult the team most directly involved.

> Think deeply before turning a disagreement into a public dispute. If necessary request mediation, trying to resolve differences in a less highly-emotional medium. If you do feel that you or your work is being attacked, take your time to breathe through before writing heated replies. Consider a 24 hour moratorium if emotional language is being used - a cooling off period is sometimes all that is needed. If you really want to go a different way, then we encourage you to publish your ideas and your work, so that it can be tried and tested.

https://nextcloud.com/code-of-conduct/

It has helped to generate a very positive environment.  What do you guys think?  Is that something we could buy into?  And perhaps incorporate into our own code?

Let me know if I can help out, or offer support.  I hope it's not too late.

**Comment by mediaprophet** [comment] 2019-02-27 05:43
Melvin,

1. I cannot delete his comments due to the manner in which google docs
works (even.thought I am the document owner)

2. I have later found that I can copy the document and this in turn removes
rhe comments, however as this has been blown out of all proportion whilst
what is seen in.The public domain is only a.portion of.what I.responded to,

I note also.that the document clearly states on.The front page that it is
an early draft,

https://docs.google.com/presentation/d/1eIkVcnOT6EK77XQz8iFOdVEc_fWbZUdQOu2QsmVxpZk/edit?usp=drivesdk

Furthermore,

The comments that were on a wholesale leading me to have to defend myself,
which is the case across all.Channels both prior to the documents
development and after it's development, inclusive to these consequential
proceeding,

Seemingly on some basis.as though I've never worked.on ledger technology,
or some other fairly poor - in.my opinion, inference that may be considered
thereafter.

Comments were also.made.on the solid economics draft which had previously
been reviewed by others, without suggestions I might add,

https://docs.google.com/document/d/1JMoqqeM4xa5lwVUgZVal4T7Y5EoLd_2zT36Ov2dia9c/edit?usp=drivesdk

And frankly, If I want to block comments on a Document I produce, that is
entirely my decisions.

If.my.documents had been developed further as to form something that had
the cooperatively / collaborative input of.other solid.members as to turn
the document into an official community text, that.may be different.

Yet.If the community was then.undermined using the same.method, comments
were unable to be removed, statement about insanity and.all.sort.of.things
that.have serious legal consequences were then brought about - well...

I've stated clearly,

I'm opting to form an alternative approach that provides me the ability
to.choose who I volunteers my time.with in anthe ecosystem that is nothing
without trust, as a sacred, hard earned set of derivatives formed through
lived experience, overtime.

In terms of whether and what repercussions effects there are to proclaiming
solid should sit on top of (somebody else's?) blockchain,

By all means  - make a copy of.my.slides and define what it.is you think,
will teach me.never to start drafting another document for this community,
directly, again.

Notwithstanding,

Anything I do.that can.help.solid, that is.The.underlying pieces
put.together in a way that protects freedom of.thought,

"Solid" is welcome to.use, but perhaps better managed via the CG.

**Comment by mediaprophet** [comment] 2019-02-27 05:53
Oh and melvin - for the sake of the community, block me.

that is what he has demanded, in effect, give him what he wants.

**Comment by mediaprophet** [comment] 2019-02-27 06:20
NB also - I find melvins notes moreover to be helpful and productive.

needless to say - i'm fairly furious, and this upset does not reflect the
high level of esteem i have for so many - whilst particularly also noting,
publicly, both Melvin and Mitzi, alongside the others....

I need to go build some work that addresses some important issues -
elsewhere.  I have vested a significant portion of my life to works that
are dependent upon the success of 'solid', and frankly, it really doesn't
matter how it gets done - there are just important qualities that need to
be incorporated and as a dear friend pia said to another when asking about
me - her accolade about me said - there are a few people in the world who
know what needs to happen, tim is one of them.

confidants - thankyou.

but this issue does need to stop burning cycles - so, I GTG.  There are an
array of 'social reputational' and broader project related 'reputational
risks' and it is evident to me to the extreme - that i have some work to do
to solve problems as to ensure we're uplifting dignity.

When there is a draft that has been appropriately vetted prior to exposure
to the community (risk management, et.al.) i'll ensure the output is made
available with the hope, that i'll benefit the community 'at large'.

**Comment by christopherreay** [comment] 2019-02-27 07:43
I haven't accused you of anything

we met on a group brought together through a mutual friend.

every single conversation we have ever had has been in front of other people. you are the only one raising the idea that I am attacking you. I have nothing to gain from attacking you..all I have done is engage in friendly, constructive communication.

**Comment by christopherreay** [comment] 2019-02-27 07:52
https://christopherreay.com/fileStorage/wat.png

just to ground again. I objected directly to the content that "I should find my own path as I attacked and take a position of advantage, and therefore am found to be untrustworthy"
since the document in question was about solid *and shared into this solid gitter channel*, I asked here what to do. it was suggested I create an issue here, by @solid-pay, who read what was written and considered @mediaprophet's words to come under the CoC umbrella.

@mediaprophet then also left every Facebook chat group we were both in, with the same (or no) comment.

the later comment that I am a "convict", also in the gitter channel is bordering on libel, and in my opinion, this behaviour needs to be addressed. as the CoC states quite clearly. I have projected no animosity towards @mediaprophet. perhaps people would review my original post in this issue, if they are interested.

**Comment by solid-pay** [comment] 2019-02-27 09:11
> it was suggested I might creat an issue here, by @solid-pay, who read what was written and considered @mediaprophet's words to come under the CoC umbrella

Not quite accurate.  

I simply suggested replacing "untrustworthy" with another word or phrase.  I didnt suggest raising an issue.  That was someone else.

**Comment by christopherreay** [comment] 2019-02-27 09:28
Oh, @solid-pay I apologise. This is not the kind of space to make that kind of mistake. Sorry again.

Here is the content to which I was referring:
solid-pay @solid-pay Feb 25 08:33
@mediaprophet please be respectful. You have a gift for words. Calling a fellow member of the community untrustworthy is not the kind of language we want to see in this community. Please choose different language. You can do better.

Mitzi László @Mitzi-Laszlo Feb 25 08:34
@christopherreay you can submit an issue to the community repo describing what happened and how it relates to the code of conduct https://github.com/solid/community/blob/master/code-of-conduct.md
You can read how this will get processed on https://github.com/solid/community

**Comment by mediaprophet** [comment] 2019-02-27 09:28
Not the only thing that's not.accurate,

But perhaps this.isn't a place to.discuss semantics...

If anything else needs to be clarified, can a request be made of the
community manager to ping me for a response.

Henceforth, pursuant to the utility of said request, should any claims be
made,my lack.of reply or engagement should not be considered in any way an
acknowledgement or approval of any comment, inferences, claims, hearsay,
old whatever.

If the best idea ever defined to.save the web is declared, and perhaps it's
a faucet crypto distribution thing, maybe it's something else.

Point is, either way,

I will not be responding unless expressly asked to, in the interests of
working Iike a  Firefighter, to make strategic choices and managing oxygen.

Google docs does not allow the document owner to delete the comments /
comments threads made by someone else.  If these comment threads initiated
by another person are deleted by that person, any child comments relating
to any such thread are also removed consequentially.

Choices, have been made there is not evidence to.suggest incapacitation for
reasons of.mental impairment played any significant role,

nowTherefore,

Please do not be offended or allow me.to be misrepresented in anyway,

As I get back.to.The task of.ensuring you are better able to manage the
permissions structures relating to your documents, your creative writings,
your communications - your infosphere and the manner through which that is
made able to be employed to cause interference patterns with your inforg -
but moreover, your reality.

We've got hungry mouths to feed...

**Comment by mikeadams1** [comment] 2019-02-27 13:38
I would like to suggest that we create a Solid Community Grievance Resolution Committee instead of what is currently taking place. Are there any thoughts on this, do you think that maybe a grievance committee would be bettor suited to deal with these types of issues? The reason I say this is because @Mitzi-Laszlo stated; "Just to be clear I will not deliver a judgement or outcome after 14 days, I will simply close the pull request...I'm afraid it's out of my remit to comment on that."

Clearly, when a member of the community has a grievance as is taking place here, it should be given the division of attention that it is due, and a binding resolution on the parties should be a reasonable expectation.

These are just the beginning of problems, and there are certainly more to come in the future and we, as the Solid Community should determine how to deal with them, and the terms of the same should be by the Solid Community.

Inrupt Inc. is a corporation headquartered in Boston, and is not the Solid Community, and therefore, I agree that @Mitzi-Laszlo (Inrupt Inc.) does not have the authority to pass any judgement on this issue, and can only close it.

Just my thoughts, hope it was helpful.

**Comment by christopherreay** [comment] 2019-02-27 14:08
to be clear the fact that room says that he has deleted the offending
comment from his document is enough for me in this case.

I think the thread speaks for itself in that regard.

I'm happy to add l engage in a conversation about group policy somewhere
else.

thank you for your time

**Comment by akuckartz** [comment] 2019-02-27 14:58
@christopherreay You can close this issue.

**Comment by melvincarvalho** [comment] 2019-03-05 12:11
I'm sensing a will from all parties to deescalate this issue.

The inadvertent public comment, has been corrected, and it is appreciated that the google platform put barriers in the way of that.

I can only apologize that this was not intercepted earlier, and allowed to stew.  The last thing we want is to lose contributors.  In retrospect this may have been better handled in the chat.

Closing this issue.  If anyone feels this is being closed prematurely, or that there are outstanding concerns, please feel free to raise.

**Comment by christopherreay** [comment] 2019-03-06 06:21
Hi, Melvin,

I appreciate your energy in this matter, however your use of the word "inadvertent" in the conclusion post, it's an idea that appears to come from you alone.

@mediaprophet maintained throughout this discourse that I had deliberately attempted to attack him.

also is the public statement in the gitter channel that I am a "convict", which has been commented on by the community, with no response from @mediaprophet.

I'm happy for the issue to fade into non existence, but not an arbitrary conclusion to be placed at the end to make it all look neat and tidy.

**Comment by christopherreay** [comment] 2019-03-06 06:22
also could you reopen this issue, and leave out open until at least the 14 day minimum period states, as per the CoC guidelines.

**Comment by melvincarvalho** [comment] 2019-03-06 08:47
@christopherreay reopened

I use the word inadvertent in order to operate in good faith.  Most of us from time to time use language or phrases that can be inappropriate.  I certainly do!  It enables us to move forward as a community, and see the good in people, if we encourage then withdraw or retract things from the public record.

> it states clearly that human rights are for all people, including convicts

This statement as I understand it, was not directed at a specific person, though its very easy to see or infer that was the case.  My interpretation of the comment, again assuming good will, was that it was a reference to the video, not to an individual.  You have made your point and it is on record.  I suggest we leave things there, but you are within your rights to peruse the matter further should you wish to.

> also could you reopen this issue, and leave out open until at least the 14 day minimum period states, as per the CoC guidelines

I am unfamiliar with this process, but will defer to the greater wisdom of @Mitzi-Laszlo and the authors, in this matter.

**Comment by christopherreay** [comment] 2019-03-06 09:00
dear @melvincarvalho,

As I said, I appreciate the energy you are trying to add.

The exact quote regarding "convict" is:
> End of the day - even relates to convicts, which is what will protect him.
This is directly aimed at me.
@mediaprophet  was asked to address this by a member of the community, and ignored that request.

Equally, there is no statement or implication from @mediaprophet that the publicness of his comments about me in the spreadsheet were "inadvertant".

I should prefer the content of the issue be left to speak for themselves.

**Comment by akuckartz** [comment] 2019-03-06 11:53
Please be aware that there are people like myself who spend time reading all these comments. I do not understand why this issue can't be closed *now*. The CoC guidelines should be modified if necessary.

**Comment by akuckartz** [comment] 2019-03-06 11:54
I have now unsubscribed this issue.

**Comment by christopherreay** [comment] 2019-03-06 12:06
its pretty standard, that how after one message that implies that the reason for the issue has been resolved "in good faith", next come the comments about how commenting that they are "not resolved" is wasting people's time.

This process is here to enable a place for communication outside of the normal stream of the community.

I strongly object to being called a "convict" in the gitter channel. That there may be no effective resolution is absolutely fine by me, but I dont see why this issue should be closed with an arbitrary conclusion that everything is fine "in good faith". 

I suggest just to leave it be, and close it in its current state as per the CoC

**Comment by melvincarvalho** [comment] 2019-03-06 12:40
@christopherreay 

> to be clear the fact that room says that he has deleted the offending comment from their document is enough for me in this case. 

My interpretation of that comment was that there was a sense of wishing the issue to be closed.  I was applying some pragmatism and a degree of judgement.

I did not interpret this comment correctly, and I am grateful for your correction.  If you feel you have been labeled a "convict", you have every right to persue the issue further.

As I say I am unfamiliar with this process, and even this CoC.  I will leave this to the judgement of @Mitzi-Laszlo, who asked this issue to be opened.

**Comment by mediaprophet** [comment] 2019-03-06 13:41
As noted prior to the ticket being created
https://gitter.im/solid/chat?at=5c73a8fcc82c68509e3167ae  i am not
interested in posting all of the supporting materials involving others in
private conversations - as everyone has human rights - EVEN CONVICTS.

The context of my statemenets, as referred to by the link was not otherwise
reflected - which i think, is poor form...

This was also otherwise clarified earlier in the thread:
https://github.com/solid/community/issues/59#issuecomment-467463700

as noted - as christopher wrote a comment my document, that was an early -
first brain-dump of a draft, as was expressly stated on the first slide -
also not presented; google does not allow the owner of a document to delete
other peoples comments, they must do this themselves.  The author can
resolve a comment, which is what i first did, but Christopher reopened it.

it appears the demand is for me to share private discussions with others,
which is against the principles of my works as those of solid as far as i
am aware. For me to breach human rights principles as to defend myself
against continued attacks which started before i responded to comments in
my personal document in a manner that was later used for further attacks -
which was then set-up with its own web-space via this comments thread - i
find, fairly reprehensible overall..

i noted, that if the matter which was at that stage - unclear publicly -
was later found to not contain behaviour by me that warranted what would be
in-effect, a fairly severe and web-addressable reprimand - that i deserved
a party.

I don't think any such thing was ever going to be on offer.   People either
stand for some form of values, or they stand for nothing.  As i made clear
to christopher prior to any of this - whilst i do not want to work with him
personally, he is of course able to work on solid quite independently of me.

seemingly, it seems he has formed the view that whether or not he wants to
work on solid, or understand what a webid is, or whatever - he should
first, do me damage - which, without arbitration or some sense
of jurisprudence - doesn't leave much good, for those seeking to do good,
whilst maintaining restraint as to preclude ones self from doing
otherwise.  That said - negligence - incorporates both acts, and lack
thereof.

so - if, what i consider to be a 'witch hunt' by formula - be allowed to
persist - i suggest at least the facts as they are publicly defined,
overtime online - be maintained - unless of course, the purpose has
something to do with rendering meaningful assistance to fantasy,
misrepresentation and the like - more broadly.

I am not going to be threatened further by christopher as to put demands on
my time via this forum. It is in-appropriate, misguided (imo) and frankly
suggests that the group has juristion over what it is i write and am
entitled to share - and the manner through which forced contributions by
others - or 'graffiti', as was noted in the document in question - be
forced upon people as a policy of 'solid management', as stimulated to be
made policy, by someone who seemingly doesn't know how to look-up a
team-members foaf profile.

If an 'official' has a problem with me, please take it up with me directly.

It was my point, at the very start, that facilitating this 'debate' in
public was inappropriate.  my position stands.

**Comment by mediaprophet** [comment] 2019-03-06 13:47
https://www.youtube.com/watch?v=zrzMhU_4m-g

**Comment by akuckartz** [comment] 2019-03-06 16:32
Unsubscribing this issue did not work - probably due to a GitHub bug. I therefore have unwatched this repository.

**Comment by christopherreay** [comment] 2019-03-08 03:26
the first comment on this issue contains the complete context within the gitter channel of the "convict" comment.

I can find no evidence for the attacks by me to which @mediaprophet is referring

**Comment by mediaprophet** [comment] 2019-03-10 01:36
https://www.apnews.com/9d43f4b74260411797043ddd391c13d8

**Comment by christopherreay** [comment] 2019-03-10 09:31
Thats interesting stuff...

we have a lot to do

**Closed** 2019-03-11 14:54 UTC
Labels: code of conduct
